image: node:latest

stages:  
  - test
  - build

test-job: 
  stage: test
  image: lironavon/docker-puppeteer-container:14.16.0
  script:
    - npm install -f
    - cd ./node_modules/puppeteer
    - npm run install
    - cd ../..
    - npm i puppeteer --save
    - npm run test

build-job: 
  stage: build 
  script:
    - npm install -f
    - npm run build
