image: ubuntu:latest

variables:
  SP_USERNAME: $SP_USERNAME
  SP_PASSWORD: $SP_PASSWORD
  SP_TENANT: $SP_TENANT
  RG: leo-ml-test
  NEW_ACR: new
  NEW_APS: new
  NEW_WEBHOOK: new
  ACR_NAME: acrloetest122
  WEBAPP_NAME: acrloeapp122
  DOCKER_IMAGE: bicep-app-service-container:latest
  HOOK_NAME: webhook1

stages:  
  - ci
  - cd

test-job: 
  stage: ci
  image: lironavon/docker-puppeteer-container:14.16.0
  script:
    - npm install -f
    - cd ./node_modules/puppeteer
    - npm run install
    - cd ../..
    - npm i puppeteer --save
    - npm run test

az-test-exist-job:
  stage: ci
  image: mcr.microsoft.com/azure-cli
  script:
    - az login --service-principal --tenant $SP_TENANT -u $SP_USERNAME -p $SP_PASSWORD
    - findmatchacr=`az acr list --query "[?name=='$ACR_NAME'].name | length(@)"`
    - if [ $findmatcher -eq 0 ]; then cond1=1; else cond1=0; fi
    - findmatchaps=`az appservice plan list --query "[?name=='asp-$WEBAPP_NAME'].name | length(@)"`
    - if [ $findmatchaps -eq 0 ]; then cond2=1; else cond2=0; fi
    - echo "cond1=$cond1" >> test.env
    - echo "cond2=$cond2" >> test.env
  artifacts:
    reports:
      dotenv: test.env

build-job: 
  stage: ci
  image: node:latest
  needs: ['test-job']
  script:
    - npm install -f
    - npm run build

deploy-acr-job:
  stage: cd
  image: mcr.microsoft.com/azure-cli
  needs: ['az-test-exist-job']
  script:
    - echo "$cond1"
    - if [ $cond1 -eq 0 ]; then exit 0; fi
    - az login --service-principal --tenant $SP_TENANT -u $SP_USERNAME -p $SP_PASSWORD
    - az deployment group create --resource-group $RG 
      --template-file ./infrastructure/bicep/main.bicep 
      --parameters acrNewOrExisting=$NEW_ACR acrName=$ACR_NAME
  dependencies:
    - az-test-exist-job
  
build-push-image-job:
  stage: cd
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker info
  needs: ['deploy-acr-job']
  script:
    - docker login $ACR_NAME.azurecr.io
      --username $SP_USERNAME
      --password $SP_PASSWORD
    - docker build -t test .
    - docker images
    - docker tag test:latest $ACR_NAME.azurecr.io/$DOCKER_IMAGE
    - docker push $ACR_NAME.azurecr.io/$DOCKER_IMAGE

deploy-app-service-job:
  stage: cd
  image: mcr.microsoft.com/azure-cli
  needs: ['az-test-exist-job', 'build-push-image-job']
  script:
    - echo "$cond2"
    - if [ $cond2 -eq 0 ]; then exit 0; fi
    - az login --service-principal --tenant $SP_TENANT -u $SP_USERNAME -p $SP_PASSWORD
    - az deployment group create --resource-group $RG 
      --template-file ./infrastructure/bicep/main.bicep 
      --parameters apsNewOrExisting=$NEW_APS 
      webAppName=$WEBAPP_NAME
      dockerImage=$DOCKER_IMAGE
      dockerRegistryHost=$ACR_NAME.azurecr.io
    - az deployment group create --resource-group $RG 
      --template-file ./infrastructure/bicep/main.bicep 
      --parameters webhookNewOrExisting=$NEW_WEBHOOK
      webAppName=$WEBAPP_NAME
      acrName=$ACR_NAME
      dockerImage=$DOCKER_IMAGE
      hookName=$HOOK_NAME
  dependencies:
    - az-test-exist-job
  