trigger:
- main

resources:
- repo: self

name: Test and Build

jobs:
- job: ci
  pool: 
    vmImage: ubuntu-latest
  container: lironavon/docker-puppeteer-container:14.16.0
  variables:
    CI: true
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -f
      cd ./node_modules/puppeteer
      npm run install
      cd ../..
      npm i puppeteer --save
    displayName: 'npm install'

  - script: |
      npm run test
    displayName: 'npm test'

- job: build
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
    
  - script: |
      npm install -f
    displayName: 'npm install'

  - script: |
      npm run build
    displayName: 'npm build'