trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'leo-tst-service-conn'
  resourceGroupName: 'exampleRG'
  location: 'eastus'
  templateFile: './infrastructure/bicep/main.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    overrideParameters: '-acrName acrleotest9789 -acrNewOrExisting new'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
