name: Deploy GCP Resources by Terraform

on:
  push: 
    branches:
      - main

env:
  ar_name: leotestgcr2126
  image_name: test

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3 

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure/terraform/gcp
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "credentials.json"
          json: ${{ secrets.GOOGLE_CREDENTIALS }}
          
      - name: move-json
        run: mv credentials.json ./infrastructure/terraform/gcp

      - name: Terraform Validate
        run: |
          terraform validate
        working-directory: ./infrastructure/terraform/gcp
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Plan
        run: |
          terraform plan -var gcp_project=${{ secrets.GCP_PROJECT_ID }} -var ar_repo_id=$ar_name
          terraform plan -var gcp_project=${{ secrets.GCP_PROJECT_ID }} -var ar_repo_id=$ar_name -var stage2_deploy=true
        working-directory: ./infrastructure/terraform/gcp
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -var gcp_project=${{ secrets.GCP_PROJECT_ID }} -var ar_repo_id=$ar_name
        working-directory: ./infrastructure/terraform/gcp
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Build, tag, and push image to GCP AR
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          gcloud auth configure-docker europe-west2-docker.pkg.dev
          docker build -t europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.ar_name }}/${{ env.image_name }}:latest .
          docker push europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.ar_name }}/${{ env.image_name }}:latest

      - name: Deploy web application
        run: |
          terraform apply -auto-approve -var gcp_project=${{ secrets.GCP_PROJECT_ID }} -var ar_repo_id=$ar_name -var stage2_deploy=true
        working-directory: ./infrastructure/terraform/gcp
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}