name: Deploy AWS Resources by Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicrop/setup-terraform@v1
        with: 
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform Format
        id: fmt
        working-directory: ./infrastructure/terraform
        run: terraform fmt -check
        
      - name: Terraform Init
        id: init
        working-directory: ./infrastructure/terraform
        run: terraform init
        
      - name: Terraform Validate
        id: validate
        working-directory: ./infrastructure/terraform
        run: terraform validate -no-color
        
      - name: Terraform Apply
        id: apply
        working-directory: ./infrastructure/terraform
        run: terraform apply -auto-approve
        
        
        
        
